version: '3.3'

services:
  application:
    build: .
    restart: always
    container_name: crud-poc
    ports:
      - 8081:8080
    depends_on:
      - db
  db:
    image: postgres
    restart: always
    container_name: database
    environment:
      POSTGRES_DB: crud-poc
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432
    volumes:
      - ./database:/docker-entrypoint-initdb.d